---
# Get Signing Key
- name: Add Nginx Signing Key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

# Update packages
- name: Run the equivalent of "apt-get update" for latest nginx
  apt:
    update_cache: yes

# Install Nginx
- name: Install Nginx
  apt:
    name: nginx
    state: latest

# Allow Nginx in UFW
- name: Allow Nginx through Firewall
  ufw:
    rule: allow
    name: 'Nginx Full'

# Add nginx.cong
- name: Add nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes

# Add Custom default Nginx Conf - Healthcheck
- name: Add Default Nginx Config
  template:
    src: default.conf
    dest: /etc/nginx/sites-available/default
    force: yes

# Add Nginx Configs
- name: Add Nginx Config for {{ item.value.name }}.{{ item.value.ext }}
  template:
    src: wordpress.conf
    dest: /etc/nginx/sites-available/{{ item.value.name }}.{{ item.value.ext }}
    force: yes
  with_dict: "{{ domains_list }}"
  notify: restart nginx

# Symlink Nginx Configs
- name: Symlink Nginx Config for {{ item.value.name }}
  file:
    src: /etc/nginx/sites-available/{{ item.value.name }}.{{ item.value.ext }}
    dest: /etc/nginx/sites-enabled/{{ item.value.name }}.{{ item.value.ext }}
    state: link
  with_dict: "{{ domains_list }}"

# Validate and Restart Nginx
- name: Validate and Restart Nginx
  raw: nginx -t
  become: yes
  register: validate_nginx
  notify: restart nginx
