---
# Find bash shell path
- name: Get Bash Shell Path
  local_action: command which bash
  become: no
  register: bash_path

# Change default shell to /bin/bash
- name: Change {{ ubuntu_user }} shell to "{{ item }}"
  user:
    name: "{{ custom_user }}"
    shell: "{{ item }}"
  become: yes
  ignore_errors: yes
  with_items:
    - "{{ bash_path.stdout }}"
  when: bash_path.changed

# Create User
- name: Creat User Group '{{ custom_user_group }}'
  group:
    name: "{{ custom_user_group }}"
    state: present

# Add User to Sudoers List
- name: Add '{{ custom_user_group }}' group to /etc/sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ custom_user_group }}'
    line: '%{{ custom_user_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# Add User to Group
- name: Create User '{{ custom_user }}' in Group '{{ custom_user_group }}'
  user:
    name: "{{ custom_user }}"
    groups: "{{ custom_user_group }}"
    append: true
    shell: /bin/bash
    state: present
    createhome: true
