- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: restart ufw
  service:
    name: ufw
    state: restarted
    enabled: yes